# Generated by Django 5.2.8 on 2025-11-11 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Children',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('diagnosis', models.CharField(max_length=255, verbose_name='Диагноз')),
                ('dream_text', models.TextField(verbose_name='Мечта (текст)')),
                ('gift', models.CharField(max_length=255, verbose_name='Подарок')),
                ('gift_price', models.IntegerField(blank=True, default=0, null=True, verbose_name='Цена подарка')),
                ('active', models.BooleanField(default=True, verbose_name='Активна')),
                ('photo', models.ImageField(upload_to='avatars/', verbose_name='Фото')),
                ('phone_number', models.CharField(max_length=30, verbose_name='Номер телефона')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Адрес')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('phone_number', models.CharField(max_length=30, verbose_name='Номер телефона')),
                ('time_to_call', models.DateTimeField(blank=True, null=True, verbose_name='Время звонка')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='children.children', verbose_name='Ребенок')),
            ],
        ),
    ]
