# Generated by Django 5.2.8 on 2025-11-14 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'verbose_name': 'Заявки'},
        ),
        migrations.AlterModelOptions(
            name='children',
            options={'verbose_name': 'Дети'},
        ),
        migrations.AddField(
            model_name='application',
            name='dream',
            field=models.TextField(blank=True, null=True, verbose_name='Мечта'),
        ),
        migrations.AddField(
            model_name='application',
            name='type',
            field=models.CharField(choices=[('DREAM', 'Мечта'), ('SELF', 'Лично'), ('ORGANIZATION', 'Организация')], default='DREAM', verbose_name='Тип заявки'),
        ),
        migrations.AlterField(
            model_name='application',
            name='child',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='children.children', verbose_name='Ребенок'),
        ),
    ]
