# Generated by Django 5.2.8 on 2025-11-14 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0002_alter_application_options_alter_children_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'verbose_name': 'Заявки', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AlterModelOptions(
            name='children',
            options={'verbose_name': 'Дети', 'verbose_name_plural': 'Дети'},
        ),
    ]
