# Generated by Django 5.2.8 on 2025-11-18 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0003_alter_application_options_alter_children_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='fulfilled',
            field=models.BooleanField(default=False),
        ),
    ]
