# Generated by Django 5.2.8 on 2025-11-18 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0004_application_fulfilled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='fulfilled',
            field=models.BooleanField(default=False, verbose_name='Выполнено'),
        ),
    ]
