# Generated by Django 5.2.8 on 2025-11-20 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0005_alter_application_fulfilled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='children',
            name='diagnosis',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Диагноз'),
        ),
        migrations.AlterField(
            model_name='children',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Номер телефона'),
        ),
    ]
